name: Test

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 18
          - 20
          - 22
    steps:
      - name: Check out repository and branch
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test
